language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jjjax/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jjjax/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  # DockerReact-env.eba-mcdpdtit.eu-west-2.elasticbeanstalk.com
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-399857389784"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
