version: '3'

services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    stdin_open: true
    # Redundant: we could've used "image" instead.
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
  # The command will be rerunning each time our files change.
    command: ["npm", "run", "test"]
